# -*- coding: utf-8 -*-
"""Model deployment and monitoring. .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CH_YLeFPspA7-S_W9JvEZOG-LM-ZqoRB

##project objective

The goal of this project is to build a machine learning model that predicts whether a customer's loan application should be approved based on information such as income, employment status, credit history, loan amount, and education level.

The project demonstrates the complete machine learning workflow, including data preprocessing, exploratory data analysis (EDA), feature engineering, model training, and performance evaluation. Several classification algorithms will be compared to identify the model that provides the most accurate predictions.

By automating the loan approval process, this project can help financial institutions make faster, more consistent, and data-driven lending decisions while reducing manual effort and improving operational efficiency.
"""

### import libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### import the train test split libraries

from sklearn.model_selection import train_test_split

#### import library to standardize

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder


### import the algorithm liraries

from sklearn.linear_model import LogisticRegression
from sklearn.cluster import KMeans
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score



### Evaluation Libraries

from sklearn.metrics import (accuracy_score, classification_report, confusion_matrix)

### Import data
data = pd.read_csv("loandata.csv")
data.head()

"""##Data Inspection"""

## first five rows of the dataset
data.head()

#last five rows of the dataset
data.tail()

### shape of the dataframe
data.shape

### Give us the summary of the data

data.info()

### To get the descriptive analysis of the data

data.describe()

"""##Duplicate Check and Missing Value Handling"""

### check for duplicates

data.duplicated().sum()

### check for missing values
data.isnull().sum()

## filling up missing data with median and mode
# Categorical columns → fill with Mode
categorical_cols = ['Gender', 'Married', 'Dependents', 'Self_Employed']
for col in categorical_cols:
    data[col] = data[col].fillna(data[col].mode()[0])

# Numerical columns → fill with Median
numeric_cols = ['LoanAmount', 'Loan_Amount_Term', 'Credit_History']
for col in numeric_cols:
    data[col] = data[col].fillna(data[col].median())

###  After Handling - Missing Values
data.isnull().sum()

"""##Feature Selection and Engineering"""

###drop loan_id column
data.drop('Loan_ID', axis=1, inplace=True)

# Create 'TotalIncome' feature by combining ApplicantIncome and CoapplicantIncome
data['TotalIncome'] = data['ApplicantIncome'] + data['CoapplicantIncome']

print("First 5 rows with new 'TotalIncome' feature:")
display(data[['ApplicantIncome', 'CoapplicantIncome', 'TotalIncome']].head())

print("Descriptive statistics for 'TotalIncome':")
display(data['TotalIncome'].describe())

data.head()

# Drop the original 'ApplicantIncome', 'CoapplicantIncome', and 'TotalIncome' columns
data.drop(['ApplicantIncome', 'CoapplicantIncome'], axis=1, inplace=True)
data.head()

"""### Detecting Outliers"""

###  Loan Amount Distribution
plt.figure(figsize=(8,5))
sns.histplot(data['LoanAmount'], bins=30, kde=True, color='skyblue')

plt.title("Loan Amount Distribution")
plt.xlabel("Loan Amount")
plt.ylabel("Frequency")

plt.show()

### Detecting Outliers in 'LoanAmount' using IQR

# Calculate Q1 (25th percentile) and Q3 (75th percentile) for 'LoanAmount'
Q1 = data['LoanAmount'].quantile(0.25)
Q3 = data['LoanAmount'].quantile(0.75)

# Calculate the Interquartile Range (IQR)
IQR = Q3 - Q1

# Define outlier bounds
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Identify outliers
outliers = data[(data['LoanAmount'] < lower_bound) | (data['LoanAmount'] > upper_bound)]

print(f"Q1 (25th percentile): {Q1}")
print(f"Q3 (75th percentile): {Q3}")
print(f"IQR: {IQR}")
print(f"Lower Bound for Outliers: {lower_bound}")
print(f"Upper Bound for Outliers: {upper_bound}")
print(f"\nNumber of outliers detected in 'LoanAmount': {len(outliers)}")

"""Here are the rows containing outliers in the 'LoanAmount' column:"""

display(outliers)

###  TotalIncome Distribution
plt.figure(figsize=(8,5))
sns.histplot(data['TotalIncome'], bins=30, kde=True, color='skyblue')

plt.title("TotalIncome Distribution")
plt.xlabel("TotalIncome")
plt.ylabel("Frequency")

plt.show()

### Detecting Outliers in 'TotalIncome:' using IQR

# Calculate Q1 (25th percentile) and Q3 (75th percentile) for 'LoanAmount'
Q1 = data['TotalIncome'].quantile(0.25)
Q3 = data['TotalIncome'].quantile(0.75)

# Calculate the Interquartile Range (IQR)
IQR = Q3 - Q1

# Define outlier bounds
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Identify outliers
outliers = data[(data['TotalIncome'] < lower_bound) | (data['TotalIncome'] > upper_bound)]

print(f"Q1 (25th percentile): {Q1}")
print(f"Q3 (75th percentile): {Q3}")
print(f"IQR: {IQR}")
print(f"Lower Bound for Outliers: {lower_bound}")
print(f"Upper Bound for Outliers: {upper_bound}")
print(f"\nNumber of outliers detected in 'LoanAmount': {len(outliers)}")

"""Here are the rows containing outliers in the 'LoanAmount' column:"""

display(outliers)

"""##Exploratory Data Analysis (EDA)"""

# Loan Status Distribution

# Shows the number of approved vs rejected loans.

plt.figure(figsize=(6, 4))  # Set the figure size
sns.countplot(x='Loan_Status', data=data, palette='Set2')  # Create the count plot with a color palette
plt.title("Loan Approval Distribution")
plt.xlabel("Loan Status (Y: Approved, N: Rejected)")  # Label for the x-axis
plt.ylabel("Number of Applicants")  # Label for the y-axis
plt.show()

# Education Effect

# Compares education level with loan approval status.

plt.figure(figsize=(7, 4))  # Set the figure size
sns.countplot(x='Education', hue='Loan_Status', data=data, palette='pastel')  # Create a grouped count plot
plt.title("Education vs Loan Status")
plt.xlabel("Education Level")  # Label for the x-axis
plt.ylabel("Number of Applicants")  # Label for the y-axis
plt.show()




Edu_count =data['Education'].value_counts()
Edu_count_percent= Edu_count/ len(data) * 100
Edu_df = pd.DataFrame({'Count': Edu_count, 'Percentage': Edu_count_percent})
Edu_df

# Gender Effect

# Compares Gender with loan approval status.

plt.figure(figsize=(7, 4))  # Set the figure size
sns.countplot(x='Gender', hue='Loan_Status', data=data, palette='pastel')  # Create a grouped count plot
plt.title("Gender vs Loan Status")
plt.xlabel("Gender")  # Label for the x-axis
plt.ylabel("Number of Applicants")  # Label for the y-axis
plt.show()

Gen_count =data['Gender'].value_counts()
Gen_count_percent= Gen_count/ len(data) * 100
Gen_df = pd.DataFrame({'Count': Gen_count, 'Percentage': Gen_count_percent})
Gen_df

# Dependent Effect

# Compares number of dependents with loan approval status.

plt.figure(figsize=(7, 4))  # Set the figure size
sns.countplot(x='Dependents', hue='Loan_Status', data=data, palette='pastel')  # Create a grouped count plot
plt.title("Dependents vs Loan Status")
plt.xlabel("Number of Dependents")  # Label for the x-axis
plt.ylabel("Number of Applicants")  # Label for the y-axis
plt.show()


Den_count =data['Dependents'].value_counts()
Den_count_percent= Den_count/ len(data) * 100
Den_df = pd.DataFrame({'Count': Den_count, 'Percentage': Den_count_percent})
Den_df

# Marriage Effect

# Compares Marriage status with loan approval status.

plt.figure(figsize=(7, 4))  # Set the figure size
sns.countplot(x='Married', hue='Loan_Status', data=data, palette='pastel')  # Create a grouped count plot
plt.title("Marriage status vs Loan Status")
plt.xlabel("Marriage status")  # Label for the x-axis
plt.ylabel("Number of Applicants")  # Label for the y-axis
plt.show()

Mar_count =data['Married'].value_counts()
Mar_count_percent= Mar_count/ len(data) * 100
Mar_df = pd.DataFrame({'Count': Mar_count, 'Percentage': Mar_count_percent})
Mar_df

# Self Employement status Effect

# ComparesSelf Employement status with loan approval status.

plt.figure(figsize=(7, 4))  # Set the figure size
sns.countplot(x='Self_Employed', hue='Loan_Status', data=data, palette='pastel')  # Create a grouped count plot
plt.title("Self_Employement vs Loan Status")
plt.xlabel("Self Employement status")  # Label for the x-axis
plt.ylabel("Number of Applicants")  # Label for the y-axis
plt.show()

SES_count =data['Self_Employed'].value_counts()
SES_count_percent= SES_count/ len(data) * 100
SES_df = pd.DataFrame({'Count': SES_count, 'Percentage': SES_count_percent})
SES_df

# Property_Area Effect

# Compares Property_Area with loan approval status.

plt.figure(figsize=(7, 4))  # Set the figure size
sns.countplot(x='Property_Area', hue='Loan_Status', data=data, palette='pastel')  # Create a grouped count plot
plt.title("Property_Area vs Loan Status")
plt.xlabel("Property_Area")  # Label for the x-axis
plt.ylabel("Number of Applicants")  # Label for the y-axis
plt.show()

Pra_count =data['Property_Area'].value_counts()
Pra_count_percent= Pra_count/ len(data) * 100
Pra_df = pd.DataFrame({'Count': Pra_count, 'Percentage': Pra_count_percent})
Pra_df

# Compares credit history with loan approval status.

plt.figure(figsize=(7, 4))
sns.countplot(x='Credit_History', hue='Loan_Status', data=data, palette='pastel')
plt.title('Credit History vs Loan Status')
plt.xlabel('Credit History (1: Good, 0: Bad)')
plt.ylabel('Number of Applicants')
plt.show()

Cre_count =data['Credit_History'].value_counts()
Cre_count_percent= Cre_count/ len(data) * 100
Cre_df = pd.DataFrame({'Count': Cre_count, 'Percentage': Cre_count_percent})
Cre_df

# Compares Loan Term with loan approval status.

plt.figure(figsize=(8,5))
sns.countplot(x='Loan_Amount_Term', hue='Loan_Status', data=data)
plt.title('Loan Term vs Loan Status')
plt.xlabel('Loan Amount Term')
plt.ylabel('Number of Applicants')
plt.show()

Lat_count =data['Loan_Amount_Term'].value_counts()
Lat_count_percent= Lat_count/ len(data) * 100
Lat_df = pd.DataFrame({'Count': Lat_count, 'Percentage':Lat_count_percent})
Lat_df



###encode the object column using label encoding
le = LabelEncoder()
cols_to_encode = ['Gender', 'Married', 'Dependents', 'Education',
                  'Self_Employed', 'Property_Area', 'Loan_Status']

for col in cols_to_encode:
    data[col] = le.fit_transform(data[col])

print('After Encoding:')
print(data.head())

### correlation
plt.figure(figsize=(8,6))

numeric_df = data.select_dtypes(include=['int64', 'float64'])

sns.heatmap(
    numeric_df.corr(),
    annot=True,
    cmap='coolwarm',
    fmt=".2f"
)

plt.title("Correlation Heatmap")

plt.show()

"""##Model training and testing."""

## split dataset into x and y

X = data.drop(columns=['Loan_Status'])
y = data['Loan_Status']

print('X shape:', X.shape)
print('y shape:', y.shape)

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

print(f'Training set: {X_train.shape}')
print(f'Testing set:  {X_test.shape}')

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

print('✅ Data is ready for modeling!')
print(f'X_train_scaled shape: {X_train_scaled.shape}')
print(f'X_test_scaled shape:  {X_test_scaled.shape}')

"""##LogisticRegression"""

logistic_model = LogisticRegression(random_state=42)
logistic_model.fit(X_train_scaled, y_train)

# Make predictions on the scaled test data
LR_pred = logistic_model.predict(X_test_scaled)

print("Predictions made successfully.")

# Evaluate the model
accuracy = accuracy_score(y_test, LR_pred)
report = classification_report(y_test, LR_pred)
conf_matrix = confusion_matrix(y_test, LR_pred)

print(f"Accuracy: {accuracy:.2f}")
print("\nClassification Report:\n", report)
print("\nConfusion Matrix:\n", conf_matrix)

"""### Logistic Regression Cross-Validation"""

from sklearn.model_selection import cross_val_score

# Perform cross-validation for Logistic Regression
logistic_model_cv = LogisticRegression(random_state=42)
scores_lr = cross_val_score(logistic_model_cv, X_train_scaled, y_train, cv=kf, scoring='accuracy')

print(f"Cross-validation Accuracy Scores (Logistic Regression): {scores_lr}")
print(f"Mean CV Accuracy (Logistic Regression): {scores_lr.mean():.2f}")
print(f"Standard Deviation of CV Accuracy (Logistic Regression): {scores_lr.std():.2f}")

"""##Decision Tree Classifier"""

# Initialize and train the Decision Tree Classifier
dtc_model = DecisionTreeClassifier(random_state=42)
dtc_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_dtc = dtc_model.predict(X_test)

# Evaluate the model
print("Decision Tree Classifier Model Evaluation:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_dtc):.4f}")
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_dtc))
print("\nClassification Report:\n", classification_report(y_test, y_pred_dtc))

"""### Decision Tree Classifier Cross-Validation"""

# Perform cross-validation for Decision Tree Classifier
dtc_model= DecisionTreeClassifier(random_state=42)
scores_dtc = cross_val_score(dtc_model, X_train, y_train, cv=kf, scoring='accuracy')

print(f"Cross-validation Accuracy Scores (Decision Tree -): {scores_dtc}")
print(f"Mean CV Accuracy (Decision Tree ): {scores_dtc.mean():.2f}")
print(f"Standard Deviation of CV Accuracy (Decision Tree): {scores_dtc.std():.2f}")

"""### SVC Model

"""

# Initialize and train the SVC model using StandardScaler scaled data
svc_model = SVC(random_state=42)
svc_model.fit(X_train_scaled, y_train)

print("Support Vector Classifier model trained successfully using StandardScaler scaled data.")

# Make predictions on the StandardScaler scaled test data
svc_pred = svc_model.predict(X_test_scaled)

print("SVC predictions made successfully.")

# Evaluate the SVC model
accuracy_svc = accuracy_score(y_test, svc_pred)
report_svc = classification_report(y_test, svc_pred)
conf_matrix_svc = confusion_matrix(y_test, svc_pred)

print(f"Accuracy (SVC ): {accuracy_svc:.2f}")
print("\nClassification Report (SVC ):\n", report_svc)
print("\nConfusion Matrix (SVC ):\n", conf_matrix_svc)

"""### SVC Cross-Validation"""

from sklearn.model_selection import cross_val_score

# Perform cross-validation for SVC
svc_model_cv = SVC(random_state=42)
scores_svc = cross_val_score(svc_model_cv, X_train_scaled, y_train, cv=kf, scoring='accuracy')

print(f"Cross-validation Accuracy Scores (SVC -): {scores_svc}")
print(f"Mean CV Accuracy (SVC -): {scores_svc.mean():.2f}")
print(f"Standard Deviation of CV Accuracy (SVC -): {scores_svc.std():.2f}")

"""##RandomForestClassifier"""

# Initialize and train the Random Forest Classifier
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)

print("Random Forest Classifier model trained successfully.")

"""### Model Evaluation: Random Forest Classifier"""

# Make predictions on the test set
y_pred_rf = rf_model.predict(X_test)

# Evaluate the model
print("Random Forest Classifier Model Evaluation:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_rf):.4f}")
print("\nClassification Report:\n", classification_report(y_test, y_pred_rf))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))

"""### Random Forest Classifier Cross-Validation"""

# Perform cross-validation for Random Forest Classifier
rf_model_cv = RandomForestClassifier(random_state=42)
scores_rf = cross_val_score(rf_model_cv, X_train, y_train, cv=kf, scoring='accuracy')

print(f"Cross-validation Accuracy Scores (Random Forest): {scores_rf}")
print(f"Mean CV Accuracy (Random Forest ): {scores_rf.mean():.2f}")
print(f"Standard Deviation of CV Accuracy (Random Forest): {scores_rf.std():.2f}")

"""##XGBClassifier"""

# Create model
model = XGBClassifier(
    random_state=42,
    eval_metric='logloss'
)

# Train
model.fit(X_train, y_train)

# Predict
y_pred_xg = model.predict(X_test)

# Evaluate the model
print("XGBClassifier Model Evaluation:")
print(f"Accuracy: {accuracy_score(y_test, y_pred_xg):.4f}")
print("\nClassification Report:\n", classification_report(y_test, y_pred_xg))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_xg))

"""### XGBClassifier Cross-Validation"""

xgb_model_cv = XGBClassifier(random_state=42, eval_metric='logloss')
scores_xgb = cross_val_score(xgb_model_cv, X_train, y_train, cv=kf, scoring='accuracy')

print(f"Cross-validation Accuracy Scores (XGBoost-): {scores_xgb}")
print(f"Mean CV Accuracy (XGBoost ): {scores_xgb.mean():.2f}")
print(f"Standard Deviation of CV Accuracy (XGBoost): {scores_xgb.std():.2f}")

"""##models comparison"""

model_comparison = pd.DataFrame({
    'Model': [
        'Logistic Regression (StandardScaler)',
        'SVC (StandardScaler)',
        'Decision Tree (Unscaled)',
        'Random Forest (Unscaled)',
        'XGBoost (Unscaled)'
    ],
    'Single-Split Accuracy': [
        accuracy_score(y_test, LR_pred),
        accuracy_score(y_test, svc_pred),
        accuracy_score(y_test, y_pred_dtc),
        accuracy_score(y_test, y_pred_rf),
        accuracy_score(y_test, y_pred_xg)
    ],
    'Mean CV Accuracy': [
        scores_lr.mean(),
        scores_svc.mean(),
        scores_dtc.mean(),
        scores_rf.mean(),
        scores_xgb.mean()
    ],
    'CV Std Dev': [
        scores_lr.std(),
        scores_svc.std(),
        scores_dtc.std(),
        scores_rf.std(),
        scores_xgb.std()
    ]
})

display(model_comparison.round(2))

import pickle

# Save model
pickle.dump(logistic_model_cv, open("loan_model.pkl", "wb"))

# Save scaler
pickle.dump(scaler, open("scaler.pkl", "wb"))

"""The model development stage began by separating the dataset into the independent variables (X) and the target variable (y). The data was then split into training and testing sets for model training and evaluation. StandardScaler was applied to standardize the numerical features. MinMaxScaler was also evaluated; however, it produced similar results and was therefore not used in the final model.
To identify the most suitable predictive model, five machine learning algorithms were trained and evaluated

##Model Performance Comparison

Five machine learning models were evaluated using both a single train-test split and 5-fold cross-validation to assess their predictive performance and generalization ability. The models compared were Logistic Regression, Support Vector Classifier (SVC), Random Forest, XGBoost, and Decision Tree.

Logistic Regression achieved the best overall performance, with a single-split accuracy of 85%, a mean cross-validation accuracy of 80%, and a cross-validation standard deviation of 0.04. These results indicate that the model not only achieved the highest predictive accuracy but also maintained consistent performance across different data partitions.

Support Vector Classifier  also performed well, achieving a single-split accuracy of 85% and a mean cross-validation accuracy of 79% with a standard deviation of 0.04. Although its performance was comparable to Logistic Regression, its slightly lower mean cross-validation accuracy placed it second overall.

Random Forest produced a single-split accuracy of 81% and a mean cross-validation accuracy of 77%, with a standard deviation of 0.05. While the model demonstrated good predictive capability, its performance was lower than that of Logistic Regression and SVC, and it exhibited slightly greater variability across the cross-validation folds.

XGBoost achieved a single-split accuracy of 77% and a mean cross-validation accuracy of 72%, with a standard deviation of 0.03. Although it was the most consistent model based on the low standard deviation, its overall predictive accuracy was lower than the other ensemble and linear models.

Decision Tree recorded the lowest performance, with a single-split accuracy of 70% and a mean cross-validation accuracy of 71%, while maintaining a standard deviation of 0.03. The relatively low accuracy suggests that the model was less effective at capturing the underlying patterns in the dataset.

in conclusion, based on the 5-fold cross-validation results, Logistic Regression with StandardScaler was selected as the best-performing model. It achieved the highest mean cross-validation accuracy (80%) while maintaining a low standard deviation (0.04), demonstrating both high predictive performance and good stability across different data partitions. Although SVC achieved the same single-split accuracy (85%), Logistic Regression produced a slightly higher mean cross-validation accuracy, making it the most reliable model for predicting loan approval in this study.
"""